inactive_text_alpha 0.85

window_padding_width 8

font_family     JetBrainsMono Nerd Font

font_size 12.0
background_opacity            1
scrollbar_handle_opacity      0
scrollbar_track_hover_opacity 0
background_blur               1
hide_window_decorations       yes

scrollback_lines              2000
remember_window_size          no
confirm_os_window_close       0
sync_to_monitor               0

cursor_shape block
cursor_beam_thickness 1.9

# BEGIN_KITTY_THEME
# shadotheme
include current-theme.conf
# END_KITTY_THEME
