# background              #161311
# foreground              #e9e1de
# selection_background    #3f2c22
# selection_foreground    #e9e1de

# Cursor
# cursor                  #dec0b2
# cursor_text_color       #161311

# URL color
# url_color               #e6beab

# Window border
# active_border_color     #dec0b2
# inactive_border_color   #4a4644
# bell_border_color       #ffb4ab

# Tab bar
# tab_bar_background      #161311
# active_tab_background   #161311
# active_tab_foreground   #dec0b2
# inactive_tab_background #161311
# inactive_tab_foreground #d7c2b9

# Marks
# mark1_background        #ff9664
# mark1_foreground        #161311
# mark2_background        #ffb4ab
# mark2_foreground        #161311

# ==================================================
# ANSI colors
# ==================================================

color0   #140a1d
color8   #a8899c

# red
color1   #B52A5B
color9   #B52A5B

# green
color2   #FF4971
color10  #FF4971

# yellow
color3   #8897F4
color11  #8897F4

# blue
color4  #FFC0CB
color12  #FFC0CB
# magenta
color5   #E9729D
color13  #E9729D

# cyan
color6   #F18FB0
color14  #F18FB0

# white
color7   #f1c4e0
color15  #f1c4e0

active_tab_font_style bold
inactive_text_alpha 0.85

window_padding_width 8

font_family     JetBrainsMono Nerd Font

font_size 12.0
background_opacity            1
scrollbar_handle_opacity      0
scrollbar_track_hover_opacity 0
background_blur               1
hide_window_decorations       yes

scrollback_lines              2000
remember_window_size          no
confirm_os_window_close       0
sync_to_monitor               0

tab_bar_style powerline


