format = """\
$git_branch$character\
"""

add_newline = true
command_timeout = 3600000

[git_branch]
symbol = " "
style = "bold fg:#F18FB0"
format = "[](fg:#140a1d)[$symbol$branch]($style)[](fg:#140a1d)"

[character]
success_symbol = "[󰣇 ](bold fg:#FF4971)"
